# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='costume',
            name='cosplayer',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
